### ISSUE TITLE
Reconcile reading DAT and TDMS data

### ISSUE THREAD

**Issue by ciozi137** [levylabpitt/LV-Data#93]
DAT requires this construction:
![image](https://user-images.githubusercontent.com/26659428/188655078-571579a9-ea70-4e1e-b6a9-302d0805abf2.png)

[key-value] where value = variant = [DBL]

TDMS:
![image](https://user-images.githubusercontent.com/26659428/188655360-d9c38c1c-7f3d-495e-8dec-7248fc21faad.png)

[key-value] where value = variant = dict = key-value2 where value2 = variant = data (always [DBL]?)

**Comment by ciozi137** [comment]
Fix looks like this:
![image](https://user-images.githubusercontent.com/26659428/213883210-8aa89cde-f0dd-41cd-877f-9954aaeadef3.png)

**Comment by jsebolt** [comment]
@ciozi137 update the data analysis template to reflect these changes

**Comment by jsebolt** [comment]
![File Load](https://github.com/user-attachments/assets/184ed659-f69d-4ebf-bb69-0e2e498156d9)
![Select channels](https://github.com/user-attachments/assets/9b0abf0c-3073-4a58-9ffe-30e50c6e8549)
